FROM 159.226.235.105:5000/centos7-py36-proxysql

WORKDIR /home/uwsgi/webserver
COPY ./ceph /etc/ceph
COPY ./proxysql.cnf /etc/proxysql.cnf
COPY entrypoint.sh /
COPY ./webserver /home/uwsgi/webserver
RUN pip3 install -r requirements.txt \
    && yum clean all \
    && rm -rf /var/cache/yum

EXPOSE 80
ENTRYPOINT ["/entrypoint.sh"]


