version: '3'
services:
    web:
        image: 10.0.200.219:5000/webserver_web
        volumes:
            - /var/log/evharbor/:/var/log/evharbor/
        ports:
            - "80:80"
        # privileged: true
        sysctls:
            - net.core.somaxconn=1024
        tty: true
        restart: always
        links:
            - db
        depends_on:
            - db
    db:
        image: 10.0.200.219:5000/webserver_db
        restart: always