FROM 159.226.91.130:5000/centos76-py36-proxysql-rados

WORKDIR /home/uwsgi/webserver

COPY ./webserver /home/uwsgi/webserver
RUN yum install -y gcc mysql-devel \
    && pip3 install -r requirements.txt \
    && yum remove gcc -y \
    && yum clean all \
    && rm -rf /var/cache/yum

COPY ./ceph /etc/ceph
COPY ./proxysql/proxysql.db /var/lib/proxysql/proxysql.db
RUN chown proxysql:proxysql /var/lib/proxysql/proxysql.db
COPY entrypoint.sh /

EXPOSE 80
ENTRYPOINT ["/entrypoint.sh"]
