FROM 159.226.235.105:5000/centos76-py368-proxysql-rados

WORKDIR /home/uwsgi/webserver

COPY ./webserver /home/uwsgi/webserver
RUN yum install -y gcc mysql-devel \
    && pip3 install -r requirements.txt \
    && yum remove gcc -y \
    && yum clean all \
    && rm -rf /var/cache/yum

COPY ./ceph /etc/ceph
COPY ./proxysql.cnf /etc/proxysql.cnf
COPY entrypoint.sh /

EXPOSE 80
ENTRYPOINT ["/entrypoint.sh"]
